project:
  type: website

website:
  title: "Shalva Kvitelashvili"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  search: true
    
      
format:
  html:
    toc: true
    theme: 
      - cosmo
      - styles.scss



execute:
  freeze: true
  keep-md: false


